### ISSUE TITLE
it works?

### ISSUE THREAD

**Issue by tomazzz369** [vampirexxxx/Game-Update-Finder#1]
hi, this script working for you? i tried to find few updates, but without success. of course updates are available. for example two latest

http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA07399/35d030ca6f64c1fda23b80983a89de6279c853b4374dfc804e4c4baaf5719feb/CUSA07399-ver.xml
http://gs2.ww.prod.dl.playstation.net/gs2/ppkgo/prod/CUSA04529/102f36addbd161e8161265b72c89065a2ca8e2a5e40ced11b4306c6419285fa7/CUSA04529-ver.xml

for both updates are available but xml says - 404 Not Found

**Comment by vampirexxxx** [comment]
Sorry this was only in testing phase, and project dropped for now. If you need updates, look for Orbismodding
